# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_auto_20170719_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='profilechange',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
