# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:47
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields
import phonenumber_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0010_auto_20170719_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, validators=[[phonenumber_field.validators.validate_international_phonenumber]]),
        ),
    ]
